services:
  backend:
    restart: always
    build: 
      dockerfile: ../docker/Dockerfile.backend
      context: ./backend
    volumes:
      - ./backend:/app
    healthcheck: 
      test: curl --fail http://localhost:8080/ping || exit 1
      interval: 5s
      timeout: 2s
      retries: 3
      start_period: 5s
    depends_on:
      postgres:
        condition: service_healthy
  frontend:
    restart: always
    build:
      dockerfile: ../docker/Dockerfile.frontend
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    depends_on:
      backend:
        condition: service_healthy
  nginx:
    restart: always
    build: 
      dockerfile: ../docker/Dockerfile.nginx
      context: ./nginx
    ports: 
      - '5173:80'
    depends_on: 
      backend:
        condition: service_healthy
  postgres:
    restart: always
    image: postgres
    environment:
      - POSTGRES_DB=user_manage
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 2s
      retries: 3
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
