services:
  backend:
    restart: always
    build: 
      dockerfile: ../docker/Dockerfile.backend
      context: ./backend
    volumes:
      - ./backend:/app
    healthcheck: 
      test: curl --fail http://localhost:8080/ping || exit 1
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 5s
  frontend:
    restart: always
    build:
      dockerfile: ../docker/Dockerfile.frontend
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    depends_on:
      backend:
        condition: service_healthy
  nginx:
    restart: always
    build: 
      dockerfile: ../docker/Dockerfile.nginx
      context: ./nginx
    ports: 
      - '5173:80'
    depends_on: 
      backend:
        condition: service_healthy
  ## add postgres service
